name: Tests - PHP/MySQL

on:
  push:
  pull_request:

jobs:
  test-host:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']
        mysql-version: ['8.0', '8.4']

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php-version }}'
          extensions: json
          coverage: none

      - name: Display PHP version
        run: php -v

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "SELECT VERSION(); SHOW DATABASES;"

      - name: Import MySQL test DB
        run: |
          mysql --host 127.0.0.1 --port 3306 -uroot -proot < ./tests/db.sql

      - name: Composer setup
        run: |
          composer validate --strict
          composer install --no-interaction --prefer-dist

      - name: Display dependencies versions
        run: composer show

      - name: Test the code
        run: ./vendor/bin/phpunit --testdox tests
